FROM nginx:alpine

# Копируем конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем статические файлы
COPY index.html /usr/share/nginx/html/
COPY product.html /usr/share/nginx/html/
COPY img /usr/share/nginx/html/img
COPY style /usr/share/nginx/html/style
COPY scripts /usr/share/nginx/html/scripts

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
