services:
  # Nginx - Reverse Proxy + фронтенд
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: shop-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge
